// ═══════════════════════════════════════════════════════════════════
// GovBot AI — Seed / Demo Data
// Used when Supabase is not yet connected or for development
// ═══════════════════════════════════════════════════════════════════

import { Tender, AwardNotice } from "@/types/tender";

export const MOCK_TENDERS: Tender[] = [
  {
    id: "1",
    externalId: "PW-26-01104201",
    title: "Translation Services — Immigration, Refugees and Citizenship Canada",
    description: "Provision of written translation services from English to French and French to English for all IRCC divisions. Approximately 2.5 million words per year across immigration policy documents, client-facing communications, internal reports, and web content.",
    department: "Immigration, Refugees and Citizenship Canada",
    category: "SRV",
    gsin: "T015A",
    closingDate: "2026-03-15",
    publicationDate: "2026-02-10",
    estimatedValue: 850000,
    solicitationType: "RFP",
    region: "National Capital Region",
    tradeAgreements: ["CFTA", "CUSMA"],
    aiCategories: ["TRANSLATION"],
    aiScore: 97,
    competitorCount: 12,
    bidComplexity: "Medium",
    source: "canadabuys",
    sourceUrl: "https://canadabuys.canada.ca/en/tender-opportunities/tender-notice/PW-26-01104201",
    status: "open",
    computedScore: 82,
    createdAt: "2026-02-10T00:00:00Z",
    updatedAt: "2026-02-13T00:00:00Z",
    aiFulfillment: {
      approach: "Deploy fine-tuned LLM with Government of Canada terminology database and TERMIUM Plus integration. EN/FR neural translation with domain-specific fine-tuning on immigration vocabulary. Human reviewer performs spot-checks on 5% sample.",
      tools: ["Claude API", "Custom terminology DB", "TERMIUM Plus API", "Quality scoring pipeline"],
      humanOversight: "1 bilingual reviewer — spot-check 5% of output, handle edge cases",
      costReduction: "78%",
      deliverySpeed: "4x faster than traditional translation teams",
      risks: ["Legal terminology edge cases", "Cultural nuance in client communications", "QA for official documents"],
      estimatedAICost: 25000,
      estimatedHumanCost: 85000,
    },
  },
  {
    id: "2",
    externalId: "PW-26-01098744",
    title: "Data Analytics and Reporting Services — Statistics Canada",
    description: "Development of automated data analysis pipelines and visualization dashboards for Census 2026 preliminary data. Includes statistical modeling, trend analysis, data quality assessment, and production of public-facing summary reports.",
    department: "Statistics Canada",
    category: "SRV",
    gsin: "D306E",
    closingDate: "2026-04-02",
    publicationDate: "2026-02-08",
    estimatedValue: 420000,
    solicitationType: "RFP",
    region: "National Capital Region",
    tradeAgreements: ["CFTA"],
    aiCategories: ["DATA_ANALYSIS"],
    aiScore: 93,
    competitorCount: 8,
    bidComplexity: "High",
    source: "canadabuys",
    sourceUrl: "https://canadabuys.canada.ca/en/tender-opportunities/tender-notice/PW-26-01098744",
    status: "open",
    computedScore: 78,
    createdAt: "2026-02-08T00:00:00Z",
    updatedAt: "2026-02-13T00:00:00Z",
    aiFulfillment: {
      approach: "AI-powered analytics pipeline ingesting Census CSV/XML datasets, performing automated statistical analysis, generating visualizations via code generation, and producing templated report narratives.",
      tools: ["Claude API (analysis + code gen)", "Python/Pandas automation", "Plotly/D3 viz generation", "Report template engine"],
      humanOversight: "1 statistician reviews methodology; 1 project manager for deliverable sign-off",
      costReduction: "65%",
      deliverySpeed: "3x faster — automated pipeline runs overnight",
      risks: ["Statistical methodology validation", "Data sensitivity/privacy compliance", "Client change requests"],
      estimatedAICost: 18000,
      estimatedHumanCost: 72000,
    },
  },
  {
    id: "3",
    externalId: "PW-26-01112033",
    title: "Communications Strategy and Content Development — Health Canada",
    description: "Development and execution of public health communications strategy including social media content, website copy, infographics, newsletter content, and public awareness campaign materials. Bilingual EN/FR. ~200 content pieces per quarter.",
    department: "Health Canada",
    category: "SRV",
    gsin: "R019B",
    closingDate: "2026-03-28",
    publicationDate: "2026-02-12",
    estimatedValue: 380000,
    solicitationType: "RFP",
    region: "National Capital Region",
    tradeAgreements: ["CFTA", "CUSMA"],
    aiCategories: ["COMMS", "TRANSLATION"],
    aiScore: 91,
    competitorCount: 18,
    bidComplexity: "Medium",
    source: "canadabuys",
    sourceUrl: "",
    status: "open",
    computedScore: 74,
    createdAt: "2026-02-12T00:00:00Z",
    updatedAt: "2026-02-13T00:00:00Z",
    aiFulfillment: {
      approach: "AI content engine generating channel-specific content from approved health messaging frameworks. Automated EN/FR translation. Content calendar automation with scheduled generation.",
      tools: ["Claude API (content generation)", "Canva API (infographics)", "Social media scheduling API", "Translation pipeline"],
      humanOversight: "1 comms director reviews/approves; 1 graphic designer for visual polish",
      costReduction: "70%",
      deliverySpeed: "5x content volume at same timeline",
      risks: ["Health misinformation risk", "Brand voice consistency", "Bilingual accuracy"],
      estimatedAICost: 15000,
      estimatedHumanCost: 55000,
    },
  },
  {
    id: "4",
    externalId: "PW-26-01089562",
    title: "Transcription and Captioning Services — House of Commons",
    description: "Real-time and post-session transcription services for parliamentary committee meetings, press conferences, and special hearings. Bilingual with speaker identification. ~1,200 hours per fiscal year. WCAG 2.1 AA accessible.",
    department: "House of Commons",
    category: "SRV",
    gsin: "T012C",
    closingDate: "2026-04-10",
    publicationDate: "2026-02-05",
    estimatedValue: 620000,
    solicitationType: "RFP",
    region: "National Capital Region",
    tradeAgreements: ["CFTA"],
    aiCategories: ["TRANSCRIPTION", "TRANSLATION"],
    aiScore: 95,
    competitorCount: 6,
    bidComplexity: "High",
    source: "canadabuys",
    sourceUrl: "",
    status: "open",
    computedScore: 80,
    createdAt: "2026-02-05T00:00:00Z",
    updatedAt: "2026-02-13T00:00:00Z",
    aiFulfillment: {
      approach: "Whisper-based ASR pipeline with parliamentary vocabulary fine-tuning. Real-time speaker diarization. Automated EN/FR subtitle generation. WCAG-compliant caption formatting.",
      tools: ["Whisper API (speech-to-text)", "Speaker diarization model", "Claude API (cleanup & translation)", "Caption formatting engine"],
      humanOversight: "2 editors — one per official language, reviewing all final output",
      costReduction: "60%",
      deliverySpeed: "Near real-time draft, final within 2 hours vs. 24-hour traditional",
      risks: ["Real-time accuracy for live sessions", "Parliamentary terminology", "MP name recognition accuracy"],
      estimatedAICost: 30000,
      estimatedHumanCost: 120000,
    },
  },
  {
    id: "5",
    externalId: "PW-26-01115887",
    title: "Policy Research and Literature Review — ESDC",
    description: "Comprehensive literature reviews and policy research papers on labor market trends, skills training effectiveness, and workforce development. 8 research papers, 4 literature reviews, and 12 policy briefs over 12 months.",
    department: "Employment and Social Development Canada",
    category: "SRV",
    gsin: "R019A",
    closingDate: "2026-03-20",
    publicationDate: "2026-02-11",
    estimatedValue: 290000,
    solicitationType: "RFP",
    region: "National Capital Region",
    tradeAgreements: ["CFTA"],
    aiCategories: ["POLICY", "WRITING"],
    aiScore: 89,
    competitorCount: 15,
    bidComplexity: "High",
    source: "canadabuys",
    sourceUrl: "",
    status: "open",
    computedScore: 68,
    createdAt: "2026-02-11T00:00:00Z",
    updatedAt: "2026-02-13T00:00:00Z",
    aiFulfillment: {
      approach: "AI-powered research pipeline: automated academic literature search and summarization, statistical data extraction from StatCan and OECD databases, structured argument construction, and citation-verified report drafting.",
      tools: ["Claude API (research synthesis)", "Academic API integrations", "StatCan data pipeline", "Citation verification engine"],
      humanOversight: "1 senior policy analyst — methodology review and quality validation on every deliverable",
      costReduction: "55%",
      deliverySpeed: "2x faster research cycle",
      risks: ["Citation accuracy critical", "Policy nuance requires expert review", "Staying current with emerging research"],
      estimatedAICost: 12000,
      estimatedHumanCost: 65000,
    },
  },
  {
    id: "6",
    externalId: "PW-26-01103290",
    title: "Training Course Development — Canada School of Public Service",
    description: "Design and development of 6 online training modules on digital literacy, data privacy, and cybersecurity awareness for federal employees. SCORM-compliant. Bilingual delivery.",
    department: "Canada School of Public Service",
    category: "SRV",
    gsin: "U099A",
    closingDate: "2026-03-31",
    publicationDate: "2026-02-07",
    estimatedValue: 175000,
    solicitationType: "RFP",
    region: "National Capital Region",
    tradeAgreements: ["CFTA"],
    aiCategories: ["TRAINING", "WRITING", "TRANSLATION"],
    aiScore: 92,
    competitorCount: 10,
    bidComplexity: "Medium",
    source: "canadabuys",
    sourceUrl: "",
    status: "open",
    computedScore: 76,
    createdAt: "2026-02-07T00:00:00Z",
    updatedAt: "2026-02-13T00:00:00Z",
    aiFulfillment: {
      approach: "AI generates structured course content from approved curricula, creates scenario-based assessments, produces SCORM packages. Bilingual content production simultaneously.",
      tools: ["Claude API (content + assessment)", "SCORM packaging automation", "Translation pipeline", "LMS integration testing"],
      humanOversight: "1 instructional designer; 1 SME for technical accuracy",
      costReduction: "68%",
      deliverySpeed: "3x faster module production",
      risks: ["Pedagogical quality assurance", "Accessibility compliance", "Cybersecurity content accuracy"],
      estimatedAICost: 8000,
      estimatedHumanCost: 32000,
    },
  },
  {
    id: "7",
    externalId: "PW-26-01099876",
    title: "Document Review and Classification — Library and Archives Canada",
    description: "Review, classification, and metadata tagging of ~50,000 digitized historical documents. Includes content summarization, subject classification per LAC taxonomy, and bilingual metadata creation.",
    department: "Library and Archives Canada",
    category: "SRV",
    gsin: "D301B",
    closingDate: "2026-04-15",
    publicationDate: "2026-02-03",
    estimatedValue: 310000,
    solicitationType: "RFP",
    region: "National Capital Region",
    tradeAgreements: ["CFTA"],
    aiCategories: ["DOCUMENT_REVIEW"],
    aiScore: 94,
    competitorCount: 4,
    bidComplexity: "Medium",
    source: "canadabuys",
    sourceUrl: "",
    status: "open",
    computedScore: 85,
    createdAt: "2026-02-03T00:00:00Z",
    updatedAt: "2026-02-13T00:00:00Z",
    aiFulfillment: {
      approach: "Vision + language AI pipeline: OCR on digitized documents, automated content classification using LAC taxonomy embeddings, metadata extraction, bilingual summary generation.",
      tools: ["Claude Vision API", "OCR pipeline", "LAC taxonomy classifier", "Metadata extraction engine"],
      humanOversight: "1 archivist validates 10% sample; handles security-classified materials",
      costReduction: "82%",
      deliverySpeed: "10x throughput — 5,000 docs/day vs. 500/day",
      risks: ["Security clearance for some documents", "Historical handwriting recognition", "Classification accuracy"],
      estimatedAICost: 10000,
      estimatedHumanCost: 30000,
    },
  },
  {
    id: "8",
    externalId: "PW-26-01108445",
    title: "Accessibility Audit and Remediation — Shared Services Canada",
    description: "WCAG 2.1 AA compliance audit of 120 federal government websites. Automated and manual testing, remediation reports, and validation re-testing.",
    department: "Shared Services Canada",
    category: "SRV",
    gsin: "D310A",
    closingDate: "2026-04-05",
    publicationDate: "2026-02-09",
    estimatedValue: 245000,
    solicitationType: "RFP",
    region: "National Capital Region",
    tradeAgreements: ["CFTA", "CUSMA"],
    aiCategories: ["AUDIT", "TESTING"],
    aiScore: 85,
    competitorCount: 7,
    bidComplexity: "High",
    source: "canadabuys",
    sourceUrl: "",
    status: "open",
    computedScore: 71,
    createdAt: "2026-02-09T00:00:00Z",
    updatedAt: "2026-02-13T00:00:00Z",
    aiFulfillment: {
      approach: "AI-powered web crawler performs automated WCAG testing across all 120 sites, generates structured violation reports with severity scoring, produces code-level remediation suggestions.",
      tools: ["AI web crawler + WCAG engine", "Claude API (reports + code fixes)", "Axe/WAVE integration", "Regression testing pipeline"],
      humanOversight: "1 WCAG specialist for manual testing; 1 UX reviewer",
      costReduction: "58%",
      deliverySpeed: "4x faster — automated scan of 120 sites in days vs. months",
      risks: ["Manual testing still required for ~30% of WCAG criteria", "Dynamic content testing", "Remediation validation"],
      estimatedAICost: 12000,
      estimatedHumanCost: 55000,
    },
  },
  {
    id: "9",
    externalId: "PW-26-01117654",
    title: "Survey Design and Analysis — Canadian Heritage",
    description: "National survey on cultural participation and digital media consumption. Survey instrument development, bilingual deployment, data collection (n=5,000), statistical analysis, and final report.",
    department: "Canadian Heritage",
    category: "SRV",
    gsin: "R019C",
    closingDate: "2026-03-25",
    publicationDate: "2026-02-13",
    estimatedValue: 195000,
    solicitationType: "RFP",
    region: "National Capital Region",
    tradeAgreements: ["CFTA"],
    aiCategories: ["SURVEY", "DATA_ANALYSIS", "WRITING"],
    aiScore: 88,
    competitorCount: 11,
    bidComplexity: "Medium",
    source: "canadabuys",
    sourceUrl: "",
    status: "open",
    computedScore: 72,
    createdAt: "2026-02-13T00:00:00Z",
    updatedAt: "2026-02-13T00:00:00Z",
    aiFulfillment: {
      approach: "AI designs survey instrument from research objectives, generates bilingual question sets, deploys via automated survey platform. AI performs cross-tabulation, sentiment analysis, statistical modeling, and report drafting.",
      tools: ["Claude API (design + analysis + report)", "Survey platform API", "Statistical analysis pipeline", "Bilingual deployment engine"],
      humanOversight: "1 survey methodologist; 1 analyst validates statistical findings",
      costReduction: "62%",
      deliverySpeed: "Analysis phase 5x faster",
      risks: ["Survey methodology must meet federal standards", "Response bias", "Open-ended response nuance"],
      estimatedAICost: 8000,
      estimatedHumanCost: 38000,
    },
  },
  {
    id: "10",
    externalId: "PW-26-01121003",
    title: "IT Security Documentation — Treasury Board Secretariat",
    description: "IT security risk assessment documentation for 25 cloud-based systems under GC Cloud Guardrails framework. Threat modeling, risk scoring, security control mapping to ITSG-33.",
    department: "Treasury Board of Canada Secretariat",
    category: "SRV",
    gsin: "D310B",
    closingDate: "2026-04-20",
    publicationDate: "2026-02-12",
    estimatedValue: 340000,
    solicitationType: "RFP",
    region: "National Capital Region",
    tradeAgreements: ["CFTA"],
    aiCategories: ["IT_CONSULTING", "DOCUMENT_REVIEW"],
    aiScore: 83,
    competitorCount: 9,
    bidComplexity: "High",
    source: "canadabuys",
    sourceUrl: "",
    status: "open",
    computedScore: 65,
    createdAt: "2026-02-12T00:00:00Z",
    updatedAt: "2026-02-13T00:00:00Z",
    aiFulfillment: {
      approach: "AI-powered TRA pipeline: automated system profiling from architecture documents, threat modeling using MITRE ATT&CK, control mapping to ITSG-33, risk scoring with quantitative methodology.",
      tools: ["Claude API (analysis + report generation)", "MITRE ATT&CK integration", "ITSG-33 control mapping DB", "Risk scoring engine"],
      humanOversight: "1 senior IT security consultant reviews every assessment",
      costReduction: "52%",
      deliverySpeed: "2.5x faster — draft TRA in hours vs. days",
      risks: ["Certified professional sign-off required", "System architecture complexity", "Evolving threat landscape"],
      estimatedAICost: 15000,
      estimatedHumanCost: 80000,
    },
  },
];

export const MOCK_AWARDS: AwardNotice[] = [
  { id: "a1", tenderId: "", title: "Translation Services — IRCC (2024-2025)", department: "Immigration, Refugees and Citizenship Canada", awardDate: "2025-04-15", vendorName: "Acme Translation Inc.", contractValue: 780000, category: "SRV", gsin: "T015A", source: "canadabuys", createdAt: "2025-04-15" },
  { id: "a2", tenderId: "", title: "Data Analysis — Statistics Canada (2024-2025)", department: "Statistics Canada", awardDate: "2025-06-20", vendorName: "DataCorp Analytics", contractValue: 450000, category: "SRV", gsin: "D306E", source: "canadabuys", createdAt: "2025-06-20" },
  { id: "a3", tenderId: "", title: "Training Development — CSPS (2024-2025)", department: "Canada School of Public Service", awardDate: "2025-03-10", vendorName: "LearnTech Solutions", contractValue: 195000, category: "SRV", gsin: "U099A", source: "canadabuys", createdAt: "2025-03-10" },
  { id: "a4", tenderId: "", title: "Web Accessibility Audit — SSC (2024-2025)", department: "Shared Services Canada", awardDate: "2025-07-05", vendorName: "AccessFirst Digital", contractValue: 210000, category: "SRV", gsin: "D310A", source: "canadabuys", createdAt: "2025-07-05" },
  { id: "a5", tenderId: "", title: "Communications Strategy — Health Canada (2024-2025)", department: "Health Canada", awardDate: "2025-05-22", vendorName: "Narrative Public Affairs", contractValue: 340000, category: "SRV", gsin: "R019B", source: "canadabuys", createdAt: "2025-05-22" },
  { id: "a6", tenderId: "", title: "Policy Research — ESDC (2024-2025)", department: "Employment and Social Development Canada", awardDate: "2025-08-14", vendorName: "Publius Research Group", contractValue: 275000, category: "SRV", gsin: "R019A", source: "canadabuys", createdAt: "2025-08-14" },
  { id: "a7", tenderId: "", title: "Document Digitization — LAC (2024-2025)", department: "Library and Archives Canada", awardDate: "2025-02-28", vendorName: "DocuScan Canada", contractValue: 290000, category: "SRV", gsin: "D301B", source: "canadabuys", createdAt: "2025-02-28" },
  { id: "a8", tenderId: "", title: "IT Security Assessment — TBS (2024-2025)", department: "Treasury Board of Canada Secretariat", awardDate: "2025-09-10", vendorName: "CyberNorth Consulting", contractValue: 310000, category: "SRV", gsin: "D310B", source: "canadabuys", createdAt: "2025-09-10" },
  { id: "a9", tenderId: "", title: "Translation Services — IRCC (2023-2024)", department: "Immigration, Refugees and Citizenship Canada", awardDate: "2024-04-20", vendorName: "Acme Translation Inc.", contractValue: 720000, category: "SRV", gsin: "T015A", source: "canadabuys", createdAt: "2024-04-20" },
  { id: "a10", tenderId: "", title: "Survey Services — Canadian Heritage (2024-2025)", department: "Canadian Heritage", awardDate: "2025-04-30", vendorName: "PollTrack Canada", contractValue: 185000, category: "SRV", gsin: "R019C", source: "canadabuys", createdAt: "2025-04-30" },
  { id: "a11", tenderId: "", title: "Transcription — House of Commons (2024-2025)", department: "House of Commons", awardDate: "2025-05-15", vendorName: "Hansard Services Ltd.", contractValue: 580000, category: "SRV", gsin: "T012C", source: "canadabuys", createdAt: "2025-05-15" },
  { id: "a12", tenderId: "", title: "Data Reporting — Statistics Canada (2023-2024)", department: "Statistics Canada", awardDate: "2024-06-10", vendorName: "DataCorp Analytics", contractValue: 395000, category: "SRV", gsin: "D306E", source: "canadabuys", createdAt: "2024-06-10" },
];
